#!/bin/bash
# Ali-CCP 数据下载脚本

DATA_DIR="/mnt/workspace/walter.wan/open_research/LiteGenRec/data/aliccp"
RAW_DIR="${DATA_DIR}/raw"

echo "=============================================="
echo "Ali-CCP 数据集下载"
echo "=============================================="
echo ""
echo "数据集信息:"
echo "  - 名称: Ali-CCP (Alibaba Click and Conversion Prediction)"
echo "  - 来源: 阿里妈妈广告"
echo "  - 规模: 127M 样本 (84M train + 43M test)"
echo "  - 标签: click + conversion"
echo ""
echo "下载步骤:"
echo ""
echo "1. 访问天池平台:"
echo "   https://tianchi.aliyun.com/dataset/408"
echo ""
echo "2. 登录阿里云账号"
echo ""
echo "3. 点击"数据下载"，下载以下文件:"
echo "   - ad_sample_skeleton_train.csv.zip (~3.8GB)"
echo "   - ad_sample_skeleton_test.csv.zip (~1.9GB)"
echo "   - common_features_train.csv"
echo "   - common_features_test.csv"
echo ""
echo "4. 解压到目录:"
echo "   ${RAW_DIR}/"
echo ""
echo "   目录结构应为:"
echo "   ${RAW_DIR}/"
echo "   ├── train/"
echo "   │   ├── common_features_train.csv"
echo "   │   └── sample_skeleton_train.csv"
echo "   └── test/"
echo "       ├── common_features_test.csv"
echo "       └── sample_skeleton_test.csv"
echo ""
echo "5. 运行数据处理:"
echo "   cd ${DATA_DIR}/.."
echo "   python repo/src/data/aliccp.py --process"
echo ""
echo "=============================================="

# 创建目录
mkdir -p "${RAW_DIR}/train"
mkdir -p "${RAW_DIR}/test"

echo "目录已创建: ${RAW_DIR}"
